<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>

        <ApplicationIcon>CommandPalette.ico</ApplicationIcon>

        <Version>0.1.0</Version>
        <FileVersion>0.1.0.0</FileVersion>
        <AssemblyVersion>0.1.0.0</AssemblyVersion>
        <InformationalVersion>0.1.0</InformationalVersion>

        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

        <Product>Command Palette</Product>
        <AssemblyTitle>Command Palette</AssemblyTitle>
        <Company>macedov</Company>
        <Description>A lightweight and customizable command palette for Windows.</Description>
    </PropertyGroup>

    <ItemGroup>
        <Using Remove="System.Windows.Forms" />
        <None Remove="CommandPalette.ico" />
        <Resource Include="CommandPalette.ico" />
    </ItemGroup>

</Project>